### ISSUE TITLE
Enhancement request: ESM version for testing apps that use custom ES Module Loaders

### ISSUE THREAD

**Issue by aral** [tape-testing/tape#573]
__Note: ES Module Loaders are experimental so I realise that per tape’s conservative approach this issue will not be considered until they are not (which is perfectly fine, I just want to document the use case so it might eventually be considered).__

## Summary

Since tape is CJS, you cannot run your tests using a custom [ES Module Loader](https://nodejs.org/docs/latest-v16.x/api/esm.html#loaders) if your app uses one.

An ESM version of tape would allow you to.

## Workaround

I’ve just released version 2.0.0 of [@small-tech/esm-tape-runner](https://github.com/small-tech/esm-tape-runner#readme) that allows you to run your tests using your custom ES Module Loader.

See: https://github.com/small-tech/esm-tape-runner#advanced-usage-with-custom-es-module-loaders

**Comment by ljharb** [comment]
ESM can import CJS, so I’m not sure why any changes are needed. Can you help me understand?

**Comment by ljharb** [comment]
I'm pretty sure this is already possible, so, closing until there's an action item for tape.
