### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ig3** [tape-testing/tape#608]
Commit 77cabebcd4b41da0083cb2c3c71105ba165debd6 introduced new URLs to package.json including URLs for the GitHub repository that yield 404 error pages for me. Is it possible that https://github.com/tape-testling/tape should be https://github.com/tape-testing/tape?

This manifests in the 'Repository' link from https://www.npmjs.com/package/tape?activeTab=versions.

**Comment by ljharb** [comment]
whoops, yep, that's indeed the case :-)
