### ISSUE TITLE
Replace `deep-equal` by `dequal` or `fast-deep-equal`

### ISSUE THREAD

**Issue by Jayllyz** [tape-testing/tape#610]
`deep-equal` has various alternatives which are lighter and faster.

https://github.com/es-tooling/module-replacements/blob/main/docs/modules/deep-equal.md

**Comment by ljharb** [comment]
However, they are less correct/robust, and in the case of dequal, don't support engines that `tape` does.

If it is possible to be lighter or faster than deep-equal, while being equally compatible and correct, the best thing for the ecosystem is to make PRs to that package.

**Comment by Raynos** [comment]
If you want to use a tape like package with zero dependencies and simple supply chain security, consider tapzero or other packages that are wholly self contained.

tape optimizes for correctness instead of for minimal lines or bytes or packages of code.
