### ISSUE TITLE
Deprecated dependencies glob@7.2.3, inflight@1.0.6

### ISSUE THREAD

**Issue by andersk** [tape-testing/tape#611]
```console
$ npm i tape
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
```

**Comment by ljharb** [comment]
Transitive deprecation warnings aren't actionable, npm shouldn't show them, and you should ignore them :-)

As for glob, we can't ever upgrade because glob 8 drops node versions tape supports. inflight comes with glob, and there's nothing I can do about that.

**Comment by Raynos** [comment]
You can use https://github.com/socketsupply/tapzero with a similar interface, no dependencies and no npm warnings.

**Comment by domoritz** [comment]
> As for glob, we can't ever upgrade because glob 8 drops node versions tape supports.

Can't you update once Node drops support for e.g. v18 (https://nodejs.org/en/about/previous-releases)?

**Comment by ljharb** [comment]
@domoritz no, node's support has no bearing on tape's.

**Comment by qualityshepherd** [comment]
Why not make a breaking change and let peeps use the old version or the new version? 

I ask because I dig Tape and also use it for E2E tests https://github.com/qualityshepherd/tappr

**Comment by ljharb** [comment]
Because that doubles the amount of unpaid maintenance work i have to do :-)
